# Generated by Django 2.0.2 on 2018-03-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180316_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imageFUN',
            new_name='image',
        ),
    ]
